# Generated by Django 4.1.5 on 2023-01-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Автор')),
                ('date_comm', models.CharField(blank=True, max_length=255, verbose_name='Дата публикации')),
                ('stars', models.CharField(blank=True, max_length=255, verbose_name='Оценка')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на статью')),
                ('bank', models.TextField(blank=True, verbose_name='Банк')),
                ('department', models.TextField(blank=True, verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['id'],
            },
        ),
    ]
