# Generated by Django 4.1.5 on 2023-01-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentsMap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='bank',
            field=models.TextField(verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_comm',
            field=models.CharField(max_length=255, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='department',
            field=models.TextField(verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(max_length=255, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Ссылка на статью'),
        ),
    ]
