# Generated by Django 4.1.5 on 2023-01-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentsMap', '0005_alter_comment_author_alter_comment_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='department',
            field=models.TextField(verbose_name='Отделение'),
        ),
    ]
