# Generated by Django 4.1.5 on 2023-01-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentsMap', '0006_alter_comment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='department',
            field=models.TextField(blank=True, verbose_name='Отделение'),
        ),
    ]
